### ISSUE TITLE
Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by lanzone1** [seedtag/gtm-universal-tag#1]
When reviewing your template we've noticed that gtmOnSuccess or gtmOnFailure are called incorrectly. This is required so that users can sequence their tags correctly.

The template calls `sendPixel(sUrl, data.gtmOnSuccess(), data.gtmOnFailure());`. This will invoke gtmOnSuccess immediately.

Perhaps this should be something like `sendPixel(sUrl, () => {data.gtmOnSuccess();}, () => {data.gtmOnFailure();});`.

Please close this issue when this is resolved. Thanks.

**Comment by martin-magakian** [comment]
Thanks for the feedback @lanzone1 

I just fixed the issue. Can you review the GTM plugin again?
Thanks

**Comment by lmolas** [comment]
@lanzone1 
I just updated metadata.yaml to point to @martin-magakian commit.

**Comment by martin-magakian** [comment]
Hello @lanzone1 I wish you a happy new year.

Did you have time to checkout this fixup?

Thanks
